[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/pay"
  to = "/pay/index.html"
  status = 200
  force = true