[functions]
  directory = "netlify/functions"

[build]
  environment = { SECRETS_SCAN_OMIT_PATHS = "app/index.html,App/index.html" }

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/pay"
  to = "/pay/index.html"
  status = 200

[[redirects]]
  from = "/connect"
  to = "/connect.html"
  status = 200

[[redirects]]
  from = "/connect/success"
  to = "/connect-success.html"
  status = 200

[[redirects]]
  from = "/connect/refresh"
  to = "/connect-refresh.html"
  status = 200
[[redirects]]
  from = "/qbo-success"
  to = "/qbo-success.html"
  status = 200